#!/bin/bash
#          ██              ██  ██
#         ░██             ░██ ░██
#   ██████░██  ██ ██   ██ ░██ ░██  ██████
#  ██░░░░ ░██ ██ ░██  ░██ ░██ ░██ ██░░░░
# ░░█████ ░████  ░██  ░██ ░██ ░██░░█████
#  ░░░░░██░██░██ ░██  ░██ ░██ ░██ ░░░░░██
#  ██████ ░██░░██░░██████ ███ ███ ██████
# ░░░░░░  ░░  ░░  ░░░░░░ ░░░ ░░░ ░░░░░░
#
# ANSI color scheme script by pyratebeard
# original `ghosts` script by pfh
#
# Initializing mod by lolilolicon from Archlinux
#

# Custom color approximating #7071d1
purple_custom=$'\e[38;2;112;113;209m'
bld=$'\e[1m'
rst=$'\e[0m'
inv=$'\e[7m'
cat << EOF

${purple_custom}  ▄█████▄    ▄█████▄    ▄█████▄    ▄█████▄    ▄█████▄    ▄█████▄
${purple_custom} ▄███████▄  ▄███████▄  ▄███████▄  ▄███████▄  ▄███████▄  ▄███████▄
${purple_custom} ██  █  ██  ██  █  ██  ██  █  ██  ██  █  ██  ██  █  ██  ██  █  ██
${purple_custom}  ███████    ███████    ███████    ███████    ███████    ███████
${purple_custom}   █ █ █      █ █ █      █ █ █      █ █ █      █ █ █      █ █ █
$bld
${purple_custom}  ▄█████▄    ▄█████▄    ▄█████▄    ▄█████▄    ▄█████▄    ▄█████▄
${purple_custom} ▄███████▄  ▄███████▄  ▄███████▄  ▄███████▄  ▄███████▄  ▄███████▄
${purple_custom} ██  █  ██  ██  █  ██  ██  █  ██  ██  █  ██  ██  █  ██  ██  █  ██
${purple_custom}  ███████    ███████    ███████    ███████    ███████    ███████
${purple_custom}   █ █ █      █ █ █      █ █ █      █ █ █      █ █ █      █ █ █
$rst
EOF

