var y=Object.defineProperty;var x=Object.getOwnPropertyDescriptor;var O=Object.getOwnPropertyNames;var $=Object.prototype.hasOwnProperty;var j=(o,a)=>{for(var n in a)y(o,n,{get:a[n],enumerable:!0})},T=(o,a,n,s)=>{if(a&&typeof a=="object"||typeof a=="function")for(let h of O(a))!$.call(o,h)&&h!==n&&y(o,h,{get:()=>a[h],enumerable:!(s=x(a,h))||s.enumerable});return o};var P=o=>T(y({},"__esModule",{value:!0}),o);var _={};j(_,{default:()=>G});module.exports=P(_);var l=require("@raycast/api");var w="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",V=o=>{o=o.replace(/\r\n/g,`
`);let a=0,n="";for(;a<o.length;a++){let s=o.charCodeAt(a);s<128?n+=String.fromCharCode(s):s>127&&s<2048?(n+=String.fromCharCode(s>>6|192),n+=String.fromCharCode(63&s|128)):(n+=String.fromCharCode(s>>12|224),n+=String.fromCharCode(s>>6&63|128),n+=String.fromCharCode(63&s|128))}return n},z=o=>{let a,n,s,h,F,g,m,u=0,A="";for(o=V(o);u<o.length;)a=o.charCodeAt(u++),n=o.charCodeAt(u++),s=o.charCodeAt(u++),h=a>>2,F=(3&a)<<4|n>>4,g=(15&n)<<2|s>>6,m=63&s,isNaN(n)?g=m=64:isNaN(s)&&(m=64),A=A+w.charAt(h)+w.charAt(F)+w.charAt(g)+w.charAt(m);return A},U=o=>typeof o=="string"?"string":typeof SVGElement<"u"&&o instanceof SVGElement?"element":void 0,D=o=>"data:image/svg+xml;base64,"+z(o),Y=o=>D(new XMLSerializer().serializeToString(o)),R=o=>{switch(U(o)){case"string":return D(o);case"element":return Y(o);default:return o}};var d=require("react");function G(){let o=[["2","4","8","16"],["32","64","128","256"],["512","1024","2048","4096"],["8192","16384","32768","65536"]],a={PLAYING:"playing",GAMEOVER:"gameover"},n=(0,d.useRef)(a.PLAYING),s=()=>Array(4).fill().map(()=>Array(4).fill().map(()=>"")),[h,F]=(0,d.useState)(()=>{let t=s(),[i,e]=[Math.floor(Math.random()*4),Math.floor(Math.random()*4)];return t[i][e]=Math.random()<.1?"4":"2",t}),g=t=>{if(t.every(i=>i.every(e=>e!==""))){let i=!0;for(let e in t)for(let r in t[e]){let c=[[-1,0],[1,0],[0,-1],[0,1]];for(let[f,p]of c)if(t[parseInt(e)+f]&&t[parseInt(e)+f][parseInt(r)+p]===t[e][r]){i=!1;break}}i&&((0,l.showToast)({title:"Game Over",style:l.Toast.Style.Failure}),n.current=a.GAMEOVER)}};(0,d.useEffect)(()=>{(async()=>{let t=await l.LocalStorage.getItem("2048board");t&&(t=JSON.parse(t),g(t),F(t))})()},[]),(0,d.useEffect)(()=>{(async()=>await l.LocalStorage.setItem("2048board",JSON.stringify(h)))()},[h]);let m=t=>{let i=!1,e=s();for(let r in e){let c=0;for(let f in e[r])t[r][f]!==""&&(e[r][c]=t[r][f],c!=f&&(i=!0),c++)}return[e,i]},u=t=>{let i=!1;for(let e=0;e<4;e++)for(let r=0;r<3;r++)t[e][r]==t[e][r+1]&&t[e][r]!==""&&(t[e][r]=String(t[e][r]*2),t[e][r+1]="",i=!0);return[t,i]},A=t=>{let i=`
    <svg width="2250" height="1000">
    <rect x="625" y="0" width="1000" height="1000" fill="#BCAC9F" rx="20" />
    `;for(let e in t){let r=t[e];for(let c in r){let f=r[c],p={2:{tile:"#EEE4DA",color:"#776E65"},4:{tile:"#EEDEC9",color:"#776E65"},8:{tile:"#F2B178",color:"#FFFFFF"},16:{tile:"#EC8E53",color:"#FFFFFF"},32:{tile:"#F47D60",color:"#FFFFFF"},64:{tile:"#F65E3B",color:"#FFFFFF"},128:{tile:"#EDCF72",color:"#FFFFFF"},256:{tile:"#F2D04B",color:"#FFFFFF"},512:{tile:"#EFC850",color:"#FFFFFF"},1024:{tile:"#EDC53F",color:"#FFFFFF"},2048:{tile:"#EDC22E",color:"#FFFFFF"}},M=Math.log(f.length)/Math.log(.96)+100;i+=`
        <rect x="${(30+213)*c+30+625}" y="${(30+213)*e+30}" width="213" height="213" fill="#${f===""?"#CCC1B4":p[f]?.tile??"#3C3A31"}" rx="20" />
        ${f!==""&&`
          <text x="${(30+213)*c+30+625+213/2}" y="${(30+213)*e+30+213/2+M/2}" height="213" width="213" font-size="${M}" fill="#${p[f]?.color??"#FFFFFF"}" dominant-baseline="middle" text-anchor="middle" startoffset="1" font-family="Helvetica Neue" font-weight="bold">${f}</text>
        `}
        `}}return i+="</svg>",`![](${R(i)})`},N=t=>{let i=0,e=null;for(let r in t)for(let c in t[r])t[r][c]===""&&(i++,Math.random()<1/i&&(e=[r,c]));if(e!==null){let r=structuredClone(t);return r[e[0]][e[1]]=Math.random()<.1?"4":"2",g(r),r}},E=()=>{let t=s(),[i,e]=[Math.floor(Math.random()*4),Math.floor(Math.random()*4)];t[i][e]=Math.random()<.1?"4":"2",F(t),n.current=a.PLAYING},S=t=>t[0].map((i,e)=>t.map(r=>r[e])).reverse(),v=t=>t[0].map((i,e)=>t.map(r=>r[e])).map(i=>i.reverse()),B=t=>t.map(i=>i.reverse()).reverse(),C=t=>{let[i,e]=m(t),[r,c]=u(i),[f,p]=m(r);return(e||c)&&(f=N(f)),f},I=t=>v(C(S(t))),L=t=>S(C(v(t))),k=t=>B(C(B(t)));return _jsx(l.Detail,{actions:_jsx(l.ActionPanel,null,n.current===a.GAMEOVER?_jsx(l.Action,{title:"Replay",onAction:E}):_jsx(_jsxFragment,null,_jsx(l.Action,{title:"Restart",icon:l.Icon.RotateClockwise,shortcut:{modifiers:["cmd","shift"],key:"r"},onAction:async()=>{await(0,l.confirmAlert)({title:"Are you sure you want to restart?",primaryAction:{title:"Restart",style:l.Alert.ActionStyle.Destructive,onAction:()=>{E()}}})}}),_jsx(l.Action,{title:"Shift Left",shortcut:{modifiers:["shift"],key:"arrowLeft"},icon:l.Icon.ArrowLeft,onAction:()=>{F(C)}}),_jsx(l.Action,{title:"Shift Right",shortcut:{modifiers:["shift"],key:"arrowRight"},icon:l.Icon.ArrowRight,onAction:()=>{F(k)}}),_jsx(l.Action,{title:"Shift Up",shortcut:{modifiers:["shift"],key:"arrowUp"},icon:l.Icon.ArrowUp,onAction:()=>{F(I)}}),_jsx(l.Action,{title:"Shift Down",shortcut:{modifiers:["shift"],key:"arrowDown"},icon:l.Icon.ArrowDown,onAction:()=>{F(L)}}))),markdown:A(h)})}
