#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
# global settings
yabai -m config                                 \
    external_bar                 on:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.15            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      1.0            \
    window_border_radius         40            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.95           \
    window_opacity               on            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 5             \
    right_padding                5             \
    window_gap                   25             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap     
yabai -m rule --add app!="^(Stickies)$" manage=off \
borders active_color=0xff736fda width=8.0 &
yabai -m config external_bar all:50:0
# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change &> /dev/null"
echo "yabai configuration loaded.."
