#!/bin/bash
source ~/.cache/wal/colors.sh # pywal scheme - update if needed
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color5 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

options=(
	style=round
	width=7.5
	hidpi=on
	active_color=0xffb5bff4
  blur_radius=7.5
)

borders "${options[@]}"
