#!/bin/sh

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after 
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.
# Author: steampunknyanja
# Source: http://crunchbang.org/forums/viewtopic.php?pid=146715#p146715
initializeANSI()
{
  esc=""

  # Custom purple color (#7071d1)
  purple="${esc}[38;2;112;113;209m"
  purpleb="${esc}[48;2;112;113;209m"

  blackf="${purple}";   redf="${purple}";    greenf="${purple}"
  yellowf="${purple}";  bluef="${purple}";   purplef="${purple}"
  cyanf="${purple}";    whitef="${purple}"
  
  blackfbright="${purple}";   redfbright="${purple}";    greenfbright="${purple}"
  yellowfbright="${purple}";  bluefbright="${purple}";   purplefbright="${purple}"
  cyanfbright="${purple}";    whitefbright="${purple}"
  
  blackb="${purpleb}";   redb="${purpleb}";    greenb="${purpleb}"
  yellowb="${purpleb}";  blueb="${purpleb}";   purpleb="${purpleb}"
  cyanb="${purpleb}";    whiteb="${purpleb}"

  boldon="${esc}[1m";    boldoff="${esc}[22m"
  italicson="${esc}[3m"; italicsoff="${esc}[23m"
  ulon="${esc}[4m";      uloff="${esc}[24m"
  invon="${esc}[7m";     invoff="${esc}[27m"

  reset="${esc}[0m"
}

# note in this first use that switching colors doesn't require a reset
# first - the new color overrides the old one.

initializeANSI

cat << EOF

 ${reset}${redf}  ██  ██   ${reset}${boldon}${redfbright}██    ${reset}${greenf}  ██  ██   ${reset}${boldon}${greenfbright}██    ${reset}${yellowf}  ██  ██   ${reset}${boldon}${yellowfbright}██    ${reset}${bluef}  ██  ██   ${reset}${boldon}${bluefbright}██    ${reset}${purplef}  ██  ██   ${reset}${boldon}${purplefbright}██    ${reset}${cyanf}  ██  ██   ${reset}${boldon}${cyanfbright}██
 ${reset}${redf}██████████ ${reset}${boldon}${redfbright}██    ${reset}${greenf}██████████ ${reset}${boldon}${greenfbright}██    ${reset}${yellowf}██████████ ${reset}${boldon}${yellowfbright}██    ${reset}${bluef}██████████ ${reset}${boldon}${bluefbright}██    ${reset}${purplef}██████████ ${reset}${boldon}${purplefbright}██    ${reset}${cyanf}██████████ ${reset}${boldon}${cyanfbright}██
 ${reset}${redf}  ██  ██   ${reset}${boldon}${redfbright}██    ${reset}${greenf}  ██  ██   ${reset}${boldon}${greenfbright}██    ${reset}${yellowf}  ██  ██   ${reset}${boldon}${yellowfbright}██    ${reset}${bluef}  ██  ██   ${reset}${boldon}${bluefbright}██    ${reset}${purplef}  ██  ██   ${reset}${boldon}${purplefbright}██    ${reset}${cyanf}  ██  ██   ${reset}${boldon}${cyanfbright}██
 ${reset}${redf}██████████       ${reset}${greenf}██████████       ${reset}${yellowf}██████████       ${reset}${bluef}██████████       ${reset}${purplef}██████████       ${reset}${cyanf}██████████   
 ${reset}${redf}  ██  ██   ${reset}${boldon}${redfbright}██    ${reset}${greenf}  ██  ██   ${reset}${boldon}${greenfbright}██    ${reset}${yellowf}  ██  ██   ${reset}${boldon}${yellowfbright}██    ${reset}${bluef}  ██  ██   ${reset}${boldon}${bluefbright}██    ${reset}${purplef}  ██  ██   ${reset}${boldon}${purplefbright}██    ${reset}${cyanf}  ██  ██   ${reset}${boldon}${cyanfbright}██ 
 ${reset}
EOF

